### PR TITLE
Don't start apps with "X-LXQt-X11-Only" under wayland

### PR DESCRIPTION
**Pull request by stefonarch**
Fixes https://github.com/lxqt/lxqt-session/issues/515
Needs a GUI later.

### CODE REVIEW

**Review by tsujan — APPROVED** [review]
Since `desktop-file-validate` doesn't allow using `OnlyShowIn` and `NotShowIn` in the same file (it says, "error: only one of OnlyShowIn and NotShowIn keys may appear in group Desktop Entry"), I guess this is the only way.

**Comment by stefonarch** [comment]
@palinek @luis-pereira thoughts?

**Comment by stefonarch** [comment]
Any objection merging this?

**Comment by stefonarch** [comment]
It will need another PR in `lxqt-globalkeys" for adding `X-LXQt-X11-Only=true` to its desktop file.

**Pull request merged**
