### PR TITLE
Add qtxdg-tools as a dependency

### PR DESCRIPTION
**Pull request by yan12125**
Needs https://github.com/lxqt/qtxdg-tools/pull/2

Per discussions starting from https://github.com/lxqt/lxqt/discussions/2139#discussioncomment-2571590, this should be merged after LXQt 1.1.0. The code is ready for review. I marked this as a draft just to prevent accidental merging.

### CODE REVIEW

**Comment by yan12125** [comment]
This is no longer blocked! I've also rebased to fix merge conflicts and expand the commit message to mention https://github.com/lxqt/lxqt/discussions/2139

**Review by tsujan — APPROVED** [review]
I think https://github.com/lxqt/libqtxdg/pull/278, https://github.com/lxqt/qtxdg-tools/pull/2 and the current PR can be merged now.

I'll set the required versions when making prerelease changes.

**Comment by tsujan** [comment]
Let's use them for a week or so before releasing their patch versions 1.1.1.

**Comment by stefonarch** [comment]
The qt6-versions of the wip  branches will be released with 1.2.0?

**Comment by tsujan** [comment]
> The qt6-versions of the wip branches will be released with 1.2.0?

Hopefully; if KF6 is ready until then.

I'll rebase my branches soon.

**Comment by tsujan** [comment]
`wip_qt6` branches are rebased now.

**Pull request merged**
