### PR TITLE
reaper: Build/Run on systems with procps-ng >= 4.0.0

### LINKED ISSUE #427: Heads up: procps-ng
Sorry, I wasn't sure where it's best to discuss this. So I chose this place here.

If I'm not mistaken we are looking for libprocps at https://github.com/lxqt/lxqt-session/blob/master/CMakeLists.txt#L36

It seems to me that procps has been replaces by [procps-ng](https://gitlab.com/procps-ng/procps).
The packageconfig file has been changed from libprocps to libproc-2.

Our tests probably will only look for the old version. Some distros will use the -ng variant as a drop in replacement I think.

Do we have any plans to update to the latest version of procps-ng ?

@tsujan @stefonarch what is the state in Arch about this?

### PR DESCRIPTION
**Pull request by palinek**
On Linux, make it possible to use libproc2 or libprocps whichever is available.

Closes #427

### CODE REVIEW

**Comment by palinek** [comment]
Rebased, sorry I didn't realize, that my sources were out of sync with current master.

**Comment by stefonarch** [comment]
There has to be an issue maybe with rebasing - using this branch on wayfire it segfaults still:
```

(gdb) where
#0  0x00007ffa0a4d0705 in XkbUseExtension () at /usr/lib/libX11.so.6
#1  0x00007ffa0a4d130a in XkbGetAutoRepeatRate () at /usr/lib/libX11.so.6

```

I was using [this patch](https://github.com/lxqt/lxqt-session/issues/427#issuecomment-1376004813) until now, which worked.

**Comment by palinek** [comment]
Rebased (again) :)

**Comment by tsujan** [comment]
Any reason why this isn't merged yet? @palinek, do you intend to change something here?

**Comment by palinek** [comment]
> do you intend to change something here?

Nope, I'm just waiting for green light from others.

**Comment by tsujan** [comment]
Let's have it in git. The more it's tested, the better.

**Pull request merged**
