### PR TITLE
Reload mouse & touchpad settings when devices are reconnected

### PR DESCRIPTION
**Pull request by yan12125**
Fixes https://github.com/lxqt/lxqt/issues/2245

### CODE REVIEW

**Review by tsujan — APPROVED** [review]
LGTM

**Comment by tsujan** [comment]
I saw the issue when I used to set the accel to -0.1: when I changed the battery of my wireless mouse (twice a year), it felt a little faster, until the next login. But I thought the batteries had a problem and ignored it ;)

**Comment by yan12125** [comment]
Gonna merge. This is a simple change and one approval is enough IMO. We still have time before the next release to identify regressions if any.

**Comment by tsujan** [comment]
> This is a simple change

It's also an important fix. The sooner such fixes are merged, the more git users might test them.

**Pull request merged**
