### PR TITLE
session: Add FreeBSD reaper logic implementation

### PR DESCRIPTION
**Pull request by palinek**
I'm not fully sure about the libutil... I couldn't find any information, if it could be installed in specific directory (and also found no pkg-config definition file) => the link is only hardcoded.

### CODE REVIEW

**Comment by palinek** [comment]
@jsm222 please, review/test...

**Comment by jsm222** [comment]
> @jsm222 please, review/test...

Thanks.  Will do as soon as possible.

**Comment by jsm222** [comment]
I tested this, it sends TERM to child processes correctly. But testing ``kill -s TERM <featherpadpid>`` to simulate the reaper feature terminates Featherpad without noticing the user of unsaved changes.. Please let me know if I am testing correctly.

**Comment by palinek** [comment]
Yes, you're testing correctly. How applications react to the received SIGTERM is beyond the scope of lxqt-session handling.

**Comment by tsujan** [comment]
Please merge it if it works under *BSD. As far as Linux is concerned, there's no change other than an additional loop, whose effect should be negligible.

**Comment by jsm222** [comment]
FYI I plan to downstream  https://github.com/lxqt/lxqt-session/commit/12619579a3d023dbb2161c9c27e49538fae4b428.patch  for lxqt-session 0.17.1 for freebsd. So a new point release is not necessary for FreeBSD's sake.. BTW, I am almost done on 0.16 -> 0.17 update of ports

**Comment by tsujan** [comment]
@palinek 
Closed by mistake? Or intentionally?

**Comment by palinek** [comment]
It's in master -> 669251f5e0b95d4c9209137932f98eccefe25cff

**Comment by tsujan** [comment]
Oh, good.

**Pull request closed without merging**
