### PR TITLE
Add DesktopNames to lxqt.desktop

### PR DESCRIPTION
**Pull request by ito32bit**
Fixes https://github.com/lxqt/lxqt/issues/1830

### CODE REVIEW

**Comment by luis-pereira** [comment]
Testing.

**Review by luis-pereira — APPROVED** [review]
GTM.
It's rather interesting that `desktop-file-validate` marks "DesktopNames" as an error.

**Comment by luis-pereira** [comment]
@ito32bit Thanks.

**Comment by ito32bit** [comment]
> It's rather interesting that `desktop-file-validate` marks "DesktopNames" as an error.

There is certainly an error.
For your reference:
DesktopNames

**Comment by luis-pereira** [comment]
@ito32bit I did the same test and came to the same conclusion.

**Pull request merged**
