### PR TITLE
Prevent cut text in header of Environment page

### PR DESCRIPTION
**Pull request by tsujan**
Closes https://github.com/lxqt/lxqt-session/issues/421

### CODE REVIEW

**Comment by stefonarch** [comment]
GTM
I experienced the first crash ever of lxqt-session: compiling this branch and opening lxqt-config-session ;)

**Comment by tsujan** [comment]
> I experienced the first crash ever of lxqt-session: 

It definitely cannot be caused by this patch. A backtrace might be informative.

**Comment by tsujan** [comment]
Oh, you probably meant running `lxqt-session` inside `lxqt-session`.

**Comment by stefonarch** [comment]
I compiled the branch and opened lxqt-config-session, that was all. I tried now to repeat it, didn't happen.

**Comment by tsujan** [comment]
Once I compiled `lxqt-session` and ran `lxqt-session` from the build dir by mistake. A mess happened.

Anyway, it's good to hunt crashes by getting backtraces with `coredumpctl gdb APP_NAME` → `where` → `q`. I clean `/var/lib/systemd/coredump` after getting a backtrace to make sure I won't get an old one later.

**Pull request merged**
